### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by MasonMax** [PRBonn/spatio-temporal-mapping#1]
Really nice work!
I want to reproduce the results of the publication. But the dataset is not provided in this repo. How to obtain the dataset?

**Comment by l00p3** [comment]
Thank you to appreciate the work! 
In the README file on the branch "iros2024" there is a section in which we explain how to reproduce the results. 
As we explain there, unfortunately, the dataset is still not publicly available, so you can send me an email and I will be more than happy to share it with you. You can find the email in that README's section.
